name: Weekly Summary (Base44)

on:
  schedule:
    - cron: "0 23 * * 0"  # Every Sunday 23:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "Force run weekly summary (ignores schedule)"
        required: false
        default: "false"

jobs:
  call-weekly-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger weeklyScheduler
        run: |
          set -e
          FORCE_INPUT="${{ github.event.inputs.force }}"
          if [ "$FORCE_INPUT" = "true" ]; then
            DATA='{"force": true}'
          else
            DATA='{}'
          fi
          curl -sS -X POST "https://base44.app/api/apps/68c07b3fd994be317e5743df/functions/weeklyScheduler" \
            -H "Content-Type: application/json" \
            ${BASE44_API_KEY:+-H "Authorization: Bearer $BASE44_API_KEY"} \
            -d "$DATA"
        env:
          BASE44_API_KEY: ${{ secrets.BASE44_API_KEY }}
